Repository sparta-team-4/TaskFlow, pull requests merged in 2025-09, with the labels that each got.

#12 feat(security) : Spring Security 설정 추가
  build.gradle
  src/main/java/com/sparta/taskflow/common/config/PropertiesConfig.java
  src/main/java/com/sparta/taskflow/common/properties/JwtSecurityProperties.java
  src/main/java/com/sparta/taskflow/common/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: ✨feat, 🔧chore

#15 feat(auth) : JWT 필터 적용
  src/main/java/com/sparta/taskflow/common/exception/FilterExceptionHandler.java
  src/main/java/com/sparta/taskflow/common/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/taskflow/common/security/WebSecurityConfig.java
  src/main/java/com/sparta/taskflow/common/security/model/CustomUserAuthentication.java
  src/main/java/com/sparta/taskflow/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/sparta/taskflow/domain/sample/controller/SampleController.java
  src/main/resources/application.yml
Labels: ✨feat

#28 feat(dashboard) : 내 작업 요약 조회 API
  src/main/java/com/sparta/taskflow/domain/dashboard/controller/DashboardController.java
  src/main/java/com/sparta/taskflow/domain/dashboard/dto/response/MyTaskSummaryResponse.java
  src/main/java/com/sparta/taskflow/domain/dashboard/service/DashboardQueryService.java
Labels: ✨feat

#33 fix(auth): login 메서드 loggable 제거
  src/main/java/com/sparta/taskflow/domain/auth/service/AuthService.java
Labels: 🐛fix

#34 feat(search) : 통합 검색 API
  src/main/java/com/sparta/taskflow/domain/search/controller/SearchController.java
  src/main/java/com/sparta/taskflow/domain/search/dto/response/SearchResponse.java
  src/main/java/com/sparta/taskflow/domain/search/service/SearchQueryService.java
  src/main/java/com/sparta/taskflow/domain/task/repository/TaskRepository.java
  src/main/java/com/sparta/taskflow/domain/task/service/TaskInternalService.java
  src/main/java/com/sparta/taskflow/domain/task/service/TaskInternalServiceImpl.java
  src/main/java/com/sparta/taskflow/domain/team/dto/TeamResponseDto.java
  src/main/java/com/sparta/taskflow/domain/team/repository/TeamRepository.java
  src/main/java/com/sparta/taskflow/domain/team/service/internal/TeamInternalService.java
  src/main/java/com/sparta/taskflow/domain/team/service/internal/TeamInternalServiceImpl.java
  src/main/java/com/sparta/taskflow/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/taskflow/domain/user/service/internal/UserInternalService.java
  src/main/java/com/sparta/taskflow/domain/user/service/internal/UserInternalServiceImpl.java
Labels: ✨feat

#36 feat: 최근 활동 조회 API
  src/main/java/com/sparta/taskflow/domain/activitylog/controller/ActivityLogController.java
  src/main/java/com/sparta/taskflow/domain/activitylog/dto/reponse/MyActivityResponse.java
  src/main/java/com/sparta/taskflow/domain/activitylog/enums/ActivityType.java
  src/main/java/com/sparta/taskflow/domain/activitylog/repository/ActivityLogRepository.java
  src/main/java/com/sparta/taskflow/domain/activitylog/service/internal/ActivityLogInternalServiceImpl.java
  src/main/java/com/sparta/taskflow/domain/user/dto/response/UserIdAndNameResponse.java
Labels: ✨feat

#37 feat(my-tasks) : 내 작업 조회 API 응답 형식 수정 및 Done 작업 제외
  src/main/java/com/sparta/taskflow/domain/dashboard/dto/response/MyTaskSummaryResponse.java
  src/main/java/com/sparta/taskflow/domain/dashboard/service/DashboardQueryService.java
Labels: ✨feat
